### ISSUE TITLE
Centralising errors catching

### ISSUE THREAD

**Issue by carlonicora** [necordjs/necord#1145]
### What is your question?

Hello,

First and foremost thanks for releasing this, much appreciated!

I am building a new version of a bot I previously created with discord.js. One of the features I previously used was a centralised error catching for all my slash commands. This includes old commands that I removed, but are still pending in the guild.

Is there a place where to create this catchall for errors?

Thanks

**Comment by NedcloarBR** [comment]
Hello! you can create a [Exception Filter](https://docs.nestjs.com/exception-filters) passaing the `DiscordAPIError` in the `@Catch` decorator
You can ignore specific errors by checking it's code from [RESTJSONErrorCodes](https://discord.com/developers/docs/topics/opcodes-and-status-codes#json-json-error-codes) that can be imported from [discord-api-types](https://discord-api-types.dev/)

**Comment by SocketSomeone** [comment]
@carlonicora Thank you for question!
@NedcloarBR  right! Just read more about [Exception Filters](https://docs.nestjs.com/exception-filters) and [global providers](https://docs.nestjs.com/exception-filters#binding-filters)

**Comment by carlonicora** [comment]
@NedcloarBR thanks for the reply.
I have one additional question.

I have created a specific exception filter which traps the call; however I have two issues:
1. If I trap a DiscordAPIError, I cannot find the interaction context, hence I cannot reply to the interaction with an error.
2. If the error is because the server still has an old slash command (not sure why the old ones are not removed), the error is not in a command, hence I cannot use the UseFilters decorator and the application crashes

Am I doing something wrong in here, or are these two edge cases?

```
import { Catch, ExceptionFilter } from '@nestjs/common';
import { DiscordAPIError } from 'discord.js';

@Catch(DiscordAPIError)
export class DiscordExceptionFilter implements ExceptionFilter {
  catch(error: DiscordAPIError) {
    console.log(error);

//I normally create an error embed and return it to Discord to warn the user
    // return new EmbedBuilder()
    //   .setColor(Colour.Red)
    //   .setTitle('Error')
    //   .setDescription(error.message);
  }
}

```

```
@CharacterCommandsDecorator()
@UseFilters(DiscordExceptionFilter)
export class CharacterDetailsCommand {
  @Subcommand({
    name: 'details',
    description: 'Get the details of a character',
  })
  public async onDetails(
    @Context() [interaction]: SlashCommandContext,
    @Options() { player }: ...
```

thanks

**Comment by SocketSomeone** [comment]
Btw, from arguments host you can get discovery item to create own typeguard of commands, events, modals and etc.
