### ISSUE TITLE
Regex and dynamic matching support for Button

### ISSUE THREAD

**Issue by AntonyGarand** [necordjs/necord#279]
### Feature

The current `@Button` decorator only accepts strings, which is limiting if we want to support dynamic button id's.
To store a bit of metadata within buttons, as they do not have a `value` property, we need to store it within the id.
For example, if we want to have a button to approve or decline an event, they have the id `approve:1234`, where `approve` is the action, and `1234` the id of the even which we want to approve.
This is loosely equivalent to a route for `/approve/:id` if it were a controller.

The idea behind this feature is to add support for dynamic matching.

### Ideal solution or implementation

The easiest solution would be to support `string | regex` and to use `buttonId.test(regex)` to match the routes.
The user can then access the id and find his own arguments using `button.id`.

An enhancement would be to support named captures: `@Button(/^approve:(?<id>\d+/)`, and add the captures or the match as a whole as an argument similarly to `@Options` for `@SlashCommands`.

### Alternative solutions or implementations

To get a simpler solution not involving regex, there could be a matching system similar to routes in controllers, where the named arguments would be described within the string: `approve/:id` to match `^approve/(?<id>.*)`
Finally this could be accessed via a decorator such as `@Param('id')` in the event listener.

This would require more work to convert strings to regexes to matches, but could be a simple approach compared to having users do their own regexes, and be similar to routes for controllers.

**Comment by SocketSomeone** [comment]
What about support for select menu, buttons, modals?

**Comment by AntonyGarand** [comment]
Select menus: We don't quite need matching for the same purpose as buttons as they can contain a value by themselves.
I'm not familiar enough with modals to position myself on them.

Overall though I believe a normalized way for everything would make the most sense: If we change buttons, might as well change everything at once, even if we don't have a use case for them at this moment.

Also, per our chat on discord, a solution like [path-to-regexp](https://www.npmjs.com/package/path-to-regexp) might be a good start to reduce the friction of regex for these type of paths.

**Comment by SocketSomeone** [comment]
Ok, ill add in 5.0.0

**Comment by SocketSomeone** [comment]
Added by https://github.com/necordjs/necord/commit/1b470b3ee80db37d285ee010153431e2a5847627. Wait publish!
