### ISSUE TITLE
Update the documentation to include sharding.

### ISSUE THREAD

**Issue by KieronWiltshire** [necordjs/necord#484]
### What is your question?

I didn't know this package existed until @jmcdo29 told me about it on the nestjs discord. It seems you support more than the `@discord-nestjs/core` package. I made a recommendation to them about adding documentation for sharding, I created a simple explanation [here](https://github.com/fjodor-rybakov/discord-nestjs/issues/911).

I think adding something similar to your documentation would be extremely beneficial. It would also be worth your time to add examples using `discord-hybrid-sharding` and `discord-cross-hosting` packages I mentioned in the explanation above as this is super important for bots that require scale.

I would be more than happy to contribute to the documentation if this suits you!

**Comment by SocketSomeone** [comment]
Hi @KieronWiltshire, thank you for your question!
Adding this information has long been planned, glad you asked!
Of course, you can contribute to the documentation, just create PR [here](https://github.com/necordjs/necord.org), replies to this [issue](https://github.com/necordjs/necord.org/issues/1)! 
Happy Coding!
