### ISSUE TITLE
Not resolving /interactions route

### ISSUE THREAD

**Issue by Simonas1331** [necordjs/necord#600]
### What is your question?

Hi, do I need to manually set up /interactions route and direct requests to discord service? From reading documentation I was under the impression that it'd be done automatically by NecordModule during setup. Could you please clarify, many thanks.

**Comment by SocketSomeone** [comment]
Hello there,

Now Discord has 2 ways to receiving an interaction:
* Via Interaction Create gateway event
* Via outgoing webhook (`/interactions` route)

**Necord now supports only first way.**

[Read More](https://discord.com/developers/docs/interactions/receiving-and-responding#receiving-an-interaction)
