### ISSUE TITLE
Collectors

### ISSUE THREAD

**Issue by wolffparkinson** [necordjs/necord#668]
### Feature

DJS collectors for :

- Message Collector
- Interaction Collector
- Reaction Collector

### Ideal solution or implementation

abstract class : 
- InteractionCollector
- MessageCollector
- ReactionCollector

methods on these classes
- onCollect
- onFilter

using interceptors, intercept the interactions/events and pass them to relevant contexts and methods

### Alternative solutions or implementations

decorators based approach :

- InteractionCollector
- MessageCollector
- ReactionCollector

**Comment by SocketSomeone** [comment]
Image from Discord Thread

![image](https://user-images.githubusercontent.com/30754373/226118500-be117d32-35e3-4d77-9024-8aae1e5e2435.png)

**Comment by SocketSomeone** [comment]
Let`s track it here: https://github.com/necordjs/necord/pull/728
