### ISSUE TITLE
The `guilds` property is broken at all commands

### ISSUE THREAD

**Issue by EliasGcf** [necordjs/necord#751]
### Issue description

After v5.7.0, the commands that receive `guilds` property are not registering this commands as Guild Application Commands, but as Global Application Commands.

At v5.6.1 it works fine.

### discord.js version

14.11.0

### nest.js version

9.4.0

### Node.js version

16.19.1

### Operating system

macOS

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_MESSAGES

**Comment by SocketSomeone** [comment]
Fixed at 5.8.4
