### ISSUE TITLE
Add sharding usage examples for discord-hybrid-sharding and discord-cross-hosting to docs

### ISSUE THREAD

**Issue by Alverrt** [necordjs/necord#761]
### Feature

It would be good to see the sharding implementation using discord-hybrid-sharding and discord-cross-hosting packages. There are already mentions to those 2 packages in docs but no details.

### Ideal solution or implementation

Add configuration examples to docs.

**Comment by SocketSomeone** [comment]
Hi there! Thank you for suggestion!
We're not familiar with the API of those packages ourselves, and it will be difficult to keep moving forward in the future. I think using these packages is a bit like Sharding in Discord.js.
